### ISSUE TITLE
machine_detection_url missing

### ISSUE THREAD

**Issue by arigon** [plivo/plivo-go#132]
Hello

in the `CallCreateParams` struct the `machine_detection_url` and `machine_detection_method` parameters are missing.
See https://www.plivo.com/docs/voice/concepts/machine-detection

Alex

**Comment by huzaif-plivo** [comment]
@arigon Thank you for the feedback! We have fixed this issue in our [latest release](https://github.com/plivo/plivo-go/releases/tag/v7.7.1) 🚀. We request you to upgrade your Plivo Go SDK to use this feature. In case of any queries, please feel free to contact our [support team](https://support.plivo.com/hc/en-us).
