### ISSUE TITLE
Polly.Marlene is missing

### ISSUE THREAD

**Issue by arigon** [plivo/plivo-go#137]
Hello

in the `getLanguageVoices()` function the second female german voice Marlene is missing.

Best regards
Alex

**Comment by huzaif-plivo** [comment]
@arigon Thank you for the feedback! We have fixed this issue in our [latest release](https://github.com/plivo/plivo-go/releases/tag/v7.7.2) 🚀. We request you to upgrade your Plivo Go SDK to use this feature. In case of any queries, please feel free to contact our [support team](https://support.plivo.com/hc/en-us).
