### ISSUE TITLE
All .go source files should be in repository root

### ISSUE THREAD

**Issue by F21** [plivo/plivo-go#2]
The `.go` files should not be nested in a `plivo` folder in the repository. Instead, all the `.go` files should be moved directly to the repository root in order for the project to follow go conventions.

Some issues caused by the code being nested in the plivo folder includes:
- Godoc does not work: https://godoc.org/github.com/github.com/plivo/plivo-go/
- Dependency management tools may not be able to import the code correctly.

**Comment by plivo-sdks** [comment]
Agreed. Missed this entirely. Will restructure it later today.

**Comment by donl** [comment]
The documentation code examples located on Plivo's site:

https://developers.plivo.com/server-side-sdks/go-sdk/

stil reference the github.com/plivo/plivo-go/plivo in the code examples.
