### ISSUE TITLE
The "total_rate" field is not exposed in the Call struct

### ISSUE THREAD

**Issue by brandonSc** [plivo/plivo-go#28]
The Call struct does not expose a field for accessing the `total_rate`,  which is returned by the REST API (as documented [here](https://www.plivo.com/docs/voice/getting-started/advanced/get-details-of-a-single-call/)). 
I was hoping to access this field after retrieving a `Call` instance from the `CallService.Get` method.

Is it possible to have this field added to the struct?

**Comment by nixonsam** [comment]
@brandonSc Thank you for bringing this up!
We have fixed it in 4.7.1 release.
