### ISSUE TITLE
testutils.go always starts a new TestServer

### ISSUE THREAD

**Issue by oliver006** [plivo/plivo-go#3]
This section here:
https://github.com/plivo/plivo-go/blob/master/plivo/testutils.go#L21-L29
always starts a new TestServer, even in the context of a normal process.

This causes the process to fail on AppEngine as listening to a port is not allowed:

```
panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: operation not permitted
```

**Comment by plivo-sdks** [comment]
@oliver006 We need that section of code to mock a test server so all tests pass. We will check if GAE allows setting up any local servers and get back to you. For the time being, you might want to skip running tests to bypass this issue.

**Comment by oliver006** [comment]
Sure, I understand why you need the test server but rhe problem is not running tests in GAE but running the http server process itself. 
The test server 1) shouldn't be brought up in each and every process that uses the library, 2) shouldn't be a global variable and 3) should just be started for each iteration of a test.

**Comment by plivo-sdks** [comment]
@oliver006 Thanks for PR. It is now merged into the project. Let me know if you are still facing this issue.
