### ISSUE TITLE
stable is broken oob

### ISSUE THREAD

**Issue by bmcgair** [plivo/plivo-go#60]
go get github.com/plivo/plivo-go
# github.com/plivo/plivo-go
../../../go/src/github.com/plivo/plivo-go/plivoclient.go:34:16: undefined: AddressService
../../../go/src/github.com/plivo/plivo-go/plivoclient.go:35:16: undefined: IdentityService

**Comment by nixonsam** [comment]
@bmcgair this was fixed and released in https://github.com/plivo/plivo-go/releases/tag/v4.1.5
