### ISSUE TITLE
Creating SMS not working

### ISSUE THREAD

**Issue by geoherna** [plivo/plivo-go#89]
Hi, As of ~12am 11 Nov 2020, began experiencing an issue where any attempts to use `client.Messages.Create` returns an error: `temporary failure`. Everything was working as expected before that estimated time provided above.

Have tried sending SMS messages outside of this SDK via http client, and sms was sent successfully. Also, started a new project with the most basic code required to send sms:

```
package main

import (
	"github.com/plivo/plivo-go"
	"log"
)

func main()  {
	client, err := plivo.NewClient("<redacted>", "<redacted>", &plivo.ClientOptions{})
	if err != nil {
		panic(err)
	}
	resp, err := client.Messages.Create(plivo.MessageCreateParams{
		Src: "<redacted>",
		Dst: "<redacted>",
		Text: "Hello, world!",
	})

	log.Println(resp, err)
}
```

and seeing this logged out: `2020/11/11 12:49:31 &{  [] } temporary failure`

**Comment by geoherna** [comment]
Update: Also tried the boilerplate code directly from Plivo's API Docs Go example and got the same:
```
package main

import "fmt"
import "github.com/plivo/plivo-go"

func main() {
	client, err := plivo.NewClient("<REDACTED>", "<REDACTED>", &plivo.ClientOptions{})
	if err != nil {
		panic(err)
	}
	response, err := client.Messages.Create(
		plivo.MessageCreateParams{
			Src: "<redacted>",
			Dst:       "<redacted>",
			Text:      "Hello, this is a sample text",
		},
	)

	fmt.Printf("Response: %#v\n", response)
	// Prints only the message_uuid
	fmt.Printf("Response: %#v\n", response.MessageUUID)
}
```

```
panic: temporary failure

goroutine 1 [running]:
main.main()
```

I also removed the panic to see if maybe some more details would be output, but had no luck:
```
Response: &plivo.MessageCreateResponseBody{Message:"", ApiID:"", MessageUUID:[]string(nil), Error:""}
Response: []string(nil)

Process finished with exit code 0
```

**Comment by aelango97** [comment]
Same issue is happening for me as well.

**Comment by aelango97** [comment]
If I did the same API call using the net/http as a request, works perfectly fine. I tried adding the User-Agent, tried removing it etc., for some reason the sdk's API calls are yielding "temporary failure"

**Comment by narayana-plivo** [comment]
@aelango97 @geoherna We will let you know, once the PR https://github.com/plivo/plivo-go/pull/90 is merged to master

**Comment by aelango97** [comment]
@narayana-plivo any updates on this?

**Comment by narayana-plivo** [comment]
@aelango97 we have released the new version. v5.4.1. Please use the latest version. Thank you
