### ISSUE TITLE
xml: Unit test does not compile

### ISSUE THREAD

**Issue by ppai-plivo** [plivo/plivo-go#97]
Reproduce:

```sh
$ cd xml
$ go test
# github.com/plivo/plivo-go/xml [github.com/plivo/plivo-go/xml.test]
./plivoxml_test.go:34: new(SpeakElement).SetContents undefined (type *SpeakElement has no field or method SetContents)
FAIL	github.com/plivo/plivo-go/xml [build failed]
```

**Comment by AustinfHunter** [comment]
I came across a similar issue when I was trying to make use of SpeakElement in a project. It seems that SpeakElement is missing the "Set" methods that are being used in the test, including SetContent, SetLanguage, SetVoice, and SetLoop.

I've seen those methods used in the Plivo docs, which could present a problem for people trying to follow along with the examples provided there. Here are some examples of these methods being used in the docs:
![plivodocs1](https://user-images.githubusercontent.com/43829479/111396127-d4e52180-8694-11eb-8737-be376257e3cb.png)
![plivodocs2](https://user-images.githubusercontent.com/43829479/111396131-d7e01200-8694-11eb-988c-4f18afd1f400.png)

Are you looking to add those methods to SpeakElement, or is AddSpeak intended to be the standard when it comes to creating a new SpeakElement? Making use of AddSpeak fixes the build errors and allows the tests to run, but I wanted to make sure that's the solution you're looking for before submitting a pull request.

**Comment by huzaif-plivo** [comment]
@AustinfHunter @ppai-plivo We addressed this issue in our most recent [release](https://github.com/plivo/plivo-go/releases/tag/v6.0.0), and you can find the relevant code snippet [here](https://www.plivo.com/docs/voice/xml/speak/#play-a-message). Feel free to contact our [support team](https://support.plivo.com/hc/en-us) if you have any questions.
